### ISSUE TITLE
zfs-auto-snapshot is not found

### ISSUE THREAD

**Issue by md61267** [bashclub/proxmox-zfs-postinstall#15]
Hi there,
during the run of the script, it states:
dpkg-query: no packages found matching zfs-auto-snapshot
'zfs-auto-snapshot' not installed yet, using script defaults...

**Comment by TheHades** [comment]
This should not be a problem because the script first checks if zfs-auto-snapshot is installed.
See https://github.com/bashclub/proxmox-zfs-postinstall/blob/main/proxmox-zfs-postinstall.sh#L126

However, the installation of the tools (https://github.com/bashclub/proxmox-zfs-postinstall/blob/main/proxmox-zfs-postinstall.sh#L6) starts at line 191 (https://github.com/bashclub/proxmox-zfs-postinstall/blob/main/proxmox-zfs-postinstall.sh#L191).

It may make sense to run the apt-process first.

**Comment by thorstenspille** [comment]
Hi,
zfs-auto-snapshot is contained in the Debian repositories since (buster / Debian 10 / Proxmox 6), if on that version or newer, there are some network or DNS issues on yout system.
